### ISSUE TITLE
Why is Exchange limited to Archive and Shared?

### ISSUE THREAD

**Issue by tinojr** [rubrikinc/microsoft-365-sizing#3]
I noticed that the Exchange statistics were way off and after looking at code I see the script is evaluating 'Archive' and 'Shared' mailboxes. Why not query all mailboxes in EXO?

$SharedMailboxes = Get-ExoMailbox -RecipientTypeDetails SharedMailbox -ResultSize Unlimited
$ArchiveMailboxes = Get-ExoMailbox -Archive -ResultSize Unlimited

**Comment by drew-russell** [comment]
Hey Tino. We leverage the admin [Usage reports ](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide)to pull the vast majority of the Exchange info. Biggest benefit of this approach is we can get everything in bulk. 

The only issue there is that the Usage reports do not included any Shared Mailbox or In-Place archive information which is why we have to query those individually.

**Comment by tinojr** [comment]
Ahh, ok. Maybe mention that on the description? Or maybe I missed it?

Thanks for the info.
Regards,
Tino

**Comment by drew-russell** [comment]
Good feedback. Just added a "What information does the script access?" section to the README that explains this in more detail. Will close out the Issue but let me know if you have any more questions.
